make-bench-beaengine:
	cl main.c -O2 -Fe:bench-beaengine-fmt -DBEA_ENGINE_STATIC -I../../libs/beaengine/include ../../libs/beaengine/lib/Windows.msvc.Release.64/Release/BeaEngine_s_l_64.lib

clean:
	rm -f bench-beaengine* *.obj
