make-bench-bddisasm:
	"$(CC)" main.c -GL -O2 -Fe:bench-bddisasm-fmt -I../../libs/bddisasm/inc ../../libs/bddisasm/bddisasm/bin/x64/Release/bddisasm.lib
	"$(CC)" main.c -GL -O2 -Fe:bench-bddisasm-no-fmt -DDISAS_BENCH_NO_FORMAT -I../../libs/bddisasm/inc ../../libs/bddisasm/bddisasm/bin/x64/Release/bddisasm.lib

clean:
	rm -f bench-bddisasm-fmt.exe bench-bddisasm-no-fmt.exe *.obj
